sudo: required
dist: xenial

branches:
  only:
    - master

# 'language: c++' doesn't help us, since it won't use the custom gcc we install
language: c++

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          packages:
            - libboost-test-dev
			- libboost-program-options-dev
			- libx11-dev
			- libxt-dev
			- libxaw7-dev
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mhier/libboost-latest'

before_script:
  - (mkdir build_dbg && cd build_dbg && cmake .. -DCMAKE_BUILD_TYPE=Debug)
  - (mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release)

script:
  - (cd build_dbg && make -j2 && ctest)
  - (cd build && make -j2 && ctest)