name: CI-Linux

on: [push]

env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}/build'
  config: 'Debug'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install boost, X11, lcov, gcovr
      run: sudo apt install libboost-test-dev libboost-program-options-dev libx11-dev libxt-dev libxaw7-dev lcov gcovr
    - name: cmake config
      run: cmake . -B ${{ env.build }}
    - name: make
      run: cmake --build ${{ env.build }}
    - name: run unit tests
      run: cmake --build ${{ env.build }} --target test
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          ${{ env.build }}/*results.xml
    - name: run coverage
      run: cmake --build ${{ env.build }} --target GAlib_lcov  
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: ${{ env.build }}/GAlib_lcov.info
        minimum-coverage: 45
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ env.build }}
        update-comment: true
        
        
        
        
        
      
      
      
      
      
