name: CI-Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: install boost, X11, lcov, gcov, doxygen
      run: sudo apt install libboost-test-dev libboost-program-options-dev libx11-dev libxt-dev libxaw7-dev lcov gcovr doxygen
      
    - name: cmake config
      run: |
        mkdir build
        cd build
        cmake ../
        
    - name: make
      run: cmake --build ./build
      
    - name: run unit tests
      run: cmake --build ./build --target test
      
    - name: run coverage
      run: cmake --build ./build --target GAlib_lcov
      
    - uses: DenverCoder1/doxygen-github-pages-action@v1.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        folder: ./build/doc/html
        config_file: ./doc/Doxyfile
      
      
      
      
      
      
      
