name: CI-Linux

on: [push]

env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}/build'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: install boost, X11, lcov, gcov, doxygen
      run: sudo apt install libboost-test-dev libboost-program-options-dev libx11-dev libxt-dev libxaw7-dev lcov gcovr doxygen graphviz mscgen dia 
      
    - name: Configure CMake
      run: cmake . -B ${{ env.build }}
      
    - uses: ammaraskar/gcc-problem-matcher@master
        
    - name: Build CMake
      run: cmake --build ${{ env.build }}
      
    - name: Run unit tests
      run: cmake --build ${{ env.build }} --target test
      
    - name: Run coverage
      run: cmake --build ${{ env.build }} --target GAlib_lcov
      
    - uses: DenverCoder1/doxygen-github-pages-action@v1.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        folder: ${{ env.build }}/doc/html
        config_file: ${{ env.build }}/Doxyfile
      
      
      
      
      
      
      
