name: CI-Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install boost, X11, lcov, gcov
      run: sudo apt install libboost-test-dev libboost-program-options-dev libx11-dev libxt-dev libxaw7-dev lcov gcovr
    - name: cmake config
      run: |
        mkdir build
        cd build
        cmake ../
    - name: make
      run: cmake --build ./build
    - name: run unit tests
      run: cmake --build ./build --target test
    - name: run coverage
      run: cmake --build ./build --target GAlib_lcov    
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: ./build/*lcov.*.info
        minimum-coverage: 90
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./build
        update-comment: true
      
      
      
      
      
