name: CI-Windows

on: [push]

env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}/build'
  config: 'Debug'

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download and install Boost
      uses: MarkusJx/install-boost@v2.4.4
      id: install-boost
      with:
          boost_version: 1.81.0
          toolset: msvc 
          platform_version: 2022
          link: shared # or static
          arch: x86 # is also for AMD64
     
    # Usually dont build doc on Windows, is done on Linux job
    #- name: Install Doxygen and Graphviz     
    #  run: choco install doxygen.install graphviz
    - name: Install opencppcoverage
      run: choco install opencppcoverage
  
    - name: Configure CMake
      run: cmake . -DCMAKE_BUILD_TYPE=${{ env.config }} -B ${{ env.build }} -DBUILD_DOC=OFF
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        
    - uses: ammaraskar/msvc-problem-matcher@master
        
    - name: Build CMake
      run: cmake --build ${{ env.build }}
    
    - name: Run unit tests
      run: cmake --build ${{ env.build }} --config ${{ env.config }} --target GAlibTest

    - name: Run coverage
      run: cmake --build ${{ env.build }} --config ${{ env.config }} --target GAlibOpencppcoverage
        









