name: CI-Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: run-vcpkg
      uses: lukka/run-vcpkg@v10.2

    #- name: install dependencies
    #  run: vcpkg install boost-test boost-program-options boost-predef --triplet x64-windows
    - name: cmake config
      run: |
        md build
        cd build
        cmake ../ -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
    - name: make
      run: cmake --build ./build
    - name: run unit tests
      working-directory: ./build
      run: ./test/Debug/GAlibTest.exe
