name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: change to galib
      run: cd galib
    - name: make build dir
      run: mkdir build
    - name: change to build dir
      run: cd build    
    - name: cmake
      run: cmake ../
    - name: make
      run: make
